plugins {
    id 'com.android.library'
}

android {
    logger.lifecycle('[cocos2d] A lifecycle info log message.')
    compileSdk 31
    buildToolsVersion '30.0.3'

//    ndkVersion '24.0.8215888'
    ndkVersion "23.1.7779620"
//    ndkVersion '21.4.7075529' (default if none specified)

    defaultConfig {
        minSdk 19
        targetSdk 30
        versionCode 31703
        versionName "3.17"
    }

    sourceSets.main {
        aidl.srcDir "../java/src"
        java.srcDir "../java/src"
        manifest.srcFile "AndroidManifest.xml"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            jniDebuggable true
            renderscriptDebuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: '../java/libs', include: ['*.jar'])
}
