apply plugin: 'com.android.library'

android {
    compileSdk 31
    ndkVersion '25.1.8937393'

    defaultConfig {
        minSdk 19
        targetSdk 31
        versionCode 31703
        versionName "3.17"
    }

    sourceSets.main {
        aidl.srcDir "../java/src"
        java.srcDir "../java/src"
        manifest.srcFile "AndroidManifest.xml"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }
}

dependencies {
    implementation fileTree(dir: '../java/libs', include: ['*.jar'])
    implementation 'androidx.startup:startup-runtime:1.0.0'
}
